### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by pratikbin** [daftcreation/gcps#21]
@Naman2706 You can now transfer ownership to https://github.com/daftcreation

**Comment by Naman2706** [comment]
![image](https://user-images.githubusercontent.com/76937210/161759379-21ada2fc-615f-47bf-ad2d-a54550e546f8.png)
@pratikbin giving me this error

**Comment by Naman2706** [comment]
@pratikbin Done!

**Comment by pratikbin** [comment]
Thank you
